version: 2

models:
  # Gold Layer Models
  - name: gold_daily_sales_summary
    description: "Daily aggregated sales performance metrics for business reporting and KPI tracking"
    columns:
      - name: sale_date
        description: "Date of sales transactions"
        tests:
          - not_null
      - name: store_location
        description: "Store location where sales occurred"
        tests:
          - not_null
      - name: product_category
        description: "Product category for sales aggregation"
        tests:
          - not_null
      - name: transaction_count
        description: "Total number of transactions for the day/location/category"
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue generated"
        tests:
          - not_null
      - name: avg_order_value
        description: "Average value per transaction"
      - name: data_quality_status
        description: "Indicator of data quality for this record"
        tests:
          - not_null
          - accepted_values:
              values: ['Valid', 'Check Required']
      - name: _gold_created_at
        description: "Timestamp when gold layer record was created"
        tests:
          - not_null

  - name: gold_customer_lifetime_value
    description: "Customer lifetime value analysis and segmentation for CRM and marketing strategies"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      - name: customer_segment
        description: "Customer segmentation based on behavior and value"
        tests:
          - not_null
          - accepted_values:
              values: ['Champion', 'Loyal Customer', 'Potential Loyalist', 'New Customer', 'At Risk']
      - name: activity_status
        description: "Customer activity status based on recent purchases"
        tests:
          - not_null
          - accepted_values:
              values: ['Active', 'Dormant', 'Inactive']
      - name: business_value_tier
        description: "Business value classification"
        tests:
          - not_null
          - accepted_values:
              values: ['High Value', 'Medium Value', 'Low Value']
      - name: total_spent
        description: "Total amount spent by customer"
        tests:
          - not_null
      - name: total_transactions
        description: "Total number of transactions by customer"
        tests:
          - not_null
      - name: current_clv
        description: "Current customer lifetime value"
        tests:
          - not_null
      - name: projected_clv
        description: "Projected customer lifetime value"

  - name: gold_product_performance
    description: "Comprehensive product performance analytics for inventory and pricing optimization"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Product name"
        tests:
          - not_null
      - name: performance_category
        description: "Product performance classification"
        tests:
          - not_null
          - accepted_values:
              values: ['Star Product', 'Strong Performer', 'Average Performer', 'Underperformer', 'No Sales']
      - name: profitability_tier
        description: "Product profitability classification"
        tests:
          - accepted_values:
              values: ['High Margin', 'Medium Margin', 'Low Margin', 'Loss Making']
      - name: business_recommendation
        description: "Automated business recommendation based on performance metrics"
        tests:
          - not_null
          - accepted_values:
              values: ['Restock Immediately', 'Consider Discontinuing', 'Review Pricing', 'Monitor Performance']
      - name: total_revenue
        description: "Total revenue generated by this product"
        tests:
          - not_null
      - name: total_profit
        description: "Total profit generated by this product"
      - name: _gold_created_at
        description: "Timestamp when gold layer record was created"
        tests:
          - not_null