name: 'mvp_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'mvp_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

seeds:
  mvp_dbt_project:
    benefit_data:
      +enabled: false
    personal_client_data:
      +enabled: false

models:
  mvp_dbt_project:
    # Medallion Architecture Configuration
    bronze:
      +materialized: table
      +tags:
        - "brons"
        - "raw"
    silver:
      +materialized: table
      +tags:
        - "zilver"
        - "getransformeerd"
    gold:
      +materialized: table
      +tags:
        - "goud"
        - "analytics"
